### ISSUE TITLE
Not able to run the demo app with positive/any result

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [stephanlensky/zendriver-docker#5]
hey there. Thx for this nice docker and project.

Sadly my setup does not come to an good result. I follow the instructions on a Ubuntu 24.04 machine.

This is my docker-compose.yaml:
```
services:
  app:
    build:
      context: .
    ports:
      - 5910:5910
    volumes:
      - swayvnc-wayvnc-certs:/certs
    environment:
      - RENDER_GROUP_GID=993 # replace with GID of the group which owns the /dev/dri/renderD128 device
      - SWAY_RESOLUTION=1920x1080
      - WAYVNC_PORT=5910
      - WAYVNC_ENABLE_AUTH=true
      - WAYVNC_USERNAME=wayvnc
      - WAYVNC_PASSWORD=wayvnc
    privileged: true

volumes:
  swayvnc-wayvnc-certs:
```

and this is the output when chrome get startet:
```
 ✔ Service app                       Built                                                                                                             1.0s
 ✔ Network zendriver-docker_default  Created                                                                                                           0.1s
 ✔ Container zendriver-docker-app-1  Created                                                                                                           0.0s
Attaching to app-1
app-1  | Setting GID 993 for group docker-render
app-1  | Waiting for sway to start...
app-1  | Found WAYLAND_DISPLAY socket: /tmp/wayland-1
app-1  | Zendriver Docker demo (zendriver 0.1.5)
app-1  | Google Chrome 131.0.6778.85 x86_64 (Linux 6.8.0-51-generic)
app-1  |
app-1  | Starting browser...
app-1  | Browser successfully started!
app-1  | Visiting https://www.browserscan.net/bot-detection
app-1  | Getting test results...
app-1  |
app-1  | Test failed! (result='') Check browser window with VNC viewer to see what happened.
app-1  |
app-1  | Demo complete.
app-1  | - Try using a VNC viewer to visit the Docker container's built-in VNC server at http://localhost:5910.
app-1  | - VNC allows for easy debugging and inspection of the browser window.
app-1  | - For some tasks which may not be fully possible to automate, it can also be used to manually interact with the browser.
app-1  |
app-1  | When you are done, press Ctrl+C to exit the demo.
Gracefully stopping... (press Ctrl+C again to force)
```

In the windows application RealVNC viewer I see this on vnc:

![Image](https://github.com/user-attachments/assets/a79e31e5-2c1b-4585-b538-467c4dff3561)

So I guess there is something wrong with the demo-script
